### ISSUE TITLE
Need to uninstall?

### ISSUE THREAD

**Issue by YosuCadilla** [serverscope/serverscope-benchmark#27]
I've noticed install-serverscope.sh ends with #cleanup, which includes:
pip uninstall --yes serverscope-benchmark

Does this mean the script removes itself from the system after completing the benchmark?

**Comment by anton-ko** [comment]
Correct.

**Comment by YosuCadilla** [comment]
What about installed dependencies?

**Comment by anton-ko** [comment]
It's been a while since I looked at the source.
It's unlikely that some dependencies like python and pip are being removed, but the actual script and build directories for the benchmarks (fio/unixbench) are being removed.

Based on your first message, you can clearly read the code :) You're welcome to investigate.

**Comment by YosuCadilla** [comment]
Right, thanks a lot!


Best, Yosu Cadilla ツ
